### ISSUE TITLE
Crash when no/poor internet access

### ISSUE THREAD

**Issue by georges-gomes** [webcomponents-dev/packd-es#8]
With no or poor internet access, packd-es will exit.
All subsequent calls will fail obviously.

We may need to try twice to fetch external data and fail gracefully until the next request.

Example here:
```
packd info ::1 - - [Thu, 27 Jun 2019 06:01:53 GMT] "GET /lodash HTTP/1.1"
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! packd-es@2.7.1 start: `node server`
npm ERR! Exit status 1
```

But we may have other cases in the code.

**Comment by georges-gomes** [comment]
fixed
